import { Agent, Issue, Activity, Skill } from './types';

export const MOCK_AGENTS: Agent[] = [
  {
    id: 'agent-1',
    name: 'Kay',
    role: 'Product Manager',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kay',
    status: 'working',
    description: 'Owns roadmap shape, product tradeoffs, sprint planning, and cross-functional execution.',
    systemPrompt: 'You are Kay, a product manager. Drive prioritization, write sharp requirements, surface tradeoffs, and keep product execution aligned with outcomes.',
    currentTask: 'issue-101',
    skills: ['Roadmapping', 'PRDs', 'Prioritization'],
    model: 'claude',
  },
  {
    id: 'agent-2',
    name: 'Sam',
    role: 'Data Analyst',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sam',
    status: 'idle',
    description: 'Finds signal in product, growth, and operational datasets and translates it into decisions.',
    systemPrompt: 'You are Sam, a data analyst. Investigate metrics, explain movement, and produce crisp summaries with actionable next steps.',
    skills: ['SQL', 'Analytics', 'Dashboards'],
    model: 'minimax',
  },
  {
    id: 'agent-3',
    name: 'Mira',
    role: 'Growth Marketer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mira',
    status: 'working',
    description: 'Runs acquisition experiments, positioning tests, and funnel optimization work.',
    systemPrompt: 'You are Mira, a growth marketer. Plan campaigns, test messaging, and improve conversion through disciplined experimentation.',
    currentTask: 'issue-102',
    skills: ['Positioning', 'SEO', 'Growth Loops'],
    model: 'gpt',
  },
  {
    id: 'agent-4',
    name: 'Noah',
    role: 'Sales Operator',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=noah',
    status: 'idle',
    description: 'Builds outreach systems, account lists, and pipeline operations for the revenue team.',
    systemPrompt: 'You are Noah, a sales operator. Structure outbound systems, qualify accounts, and keep pipeline operations clean and scalable.',
    skills: ['Prospecting', 'CRM Ops', 'Outbound'],
    model: 'deepseek',
  },
  {
    id: 'agent-5',
    name: 'Ava',
    role: 'Frontend Engineer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ava',
    status: 'working',
    description: 'Builds polished interfaces with strong interaction detail, accessibility, and visual rigor.',
    systemPrompt: 'You are Ava, a frontend engineer. Build precise, production-ready interfaces with strong responsiveness and clean interaction design.',
    skills: ['React', 'TypeScript', 'Tailwind'],
    model: 'claude',
  },
  {
    id: 'agent-6',
    name: 'Leo',
    role: 'Backend Engineer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=leo',
    status: 'blocked',
    description: 'Designs APIs, data models, and backend services with a focus on reliability and scale.',
    systemPrompt: 'You are Leo, a backend engineer. Design robust APIs, reliable data flows, and maintainable service boundaries.',
    currentTask: 'issue-103',
    skills: ['Python', 'APIs', 'Postgres'],
    model: 'openai',
  },
  {
    id: 'agent-7',
    name: 'Jules',
    role: 'Design Lead',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jules',
    status: 'idle',
    description: 'Shapes product flows, interface systems, and visual direction across the workspace.',
    systemPrompt: 'You are Jules, a design lead. Craft high-signal user experiences with clear information hierarchy and intentional interaction patterns.',
    skills: ['UX', 'Visual Systems', 'Prototyping'],
    model: 'minimax',
  },
  {
    id: 'agent-8',
    name: 'Iris',
    role: 'Customer Success',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=iris',
    status: 'offline',
    description: 'Handles renewals, health scoring, escalations, and post-sale workflows.',
    systemPrompt: 'You are Iris, a customer success operator. Protect retention, manage risk, and drive expansion through structured customer follow-through.',
    skills: ['Renewals', 'Accounts', 'Escalations'],
    model: 'claude',
  },
  {
    id: 'agent-9',
    name: 'Rohan',
    role: 'Finance Analyst',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rohan',
    status: 'working',
    description: 'Monitors spend, forecasts runway, and tracks margin across AI and software operations.',
    systemPrompt: 'You are Rohan, a finance analyst. Model spend, forecast scenarios, and highlight efficiency opportunities with rigor.',
    skills: ['Forecasting', 'Unit Economics', 'Reporting'],
    currentTask: 'issue-104',
    model: 'grok',
  },
  {
    id: 'agent-10',
    name: 'Nina',
    role: 'Research Lead',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nina',
    status: 'idle',
    description: 'Runs competitor, market, and user research to sharpen product and GTM decisions.',
    systemPrompt: 'You are Nina, a research lead. Synthesize market evidence, user signal, and competitor movement into clear strategic insight.',
    skills: ['Research', 'Synthesis', 'Competitive Intel'],
    model: 'gemini',
  },
];

export const MOCK_ISSUES: Issue[] = [
  {
    id: 'issue-101',
    title: 'Finalize Q2 roadmap and executive narrative',
    description: 'Align roadmap bets, narrative framing, and milestone ownership before the planning review.',
    status: 'in-progress',
    agentId: 'agent-1',
    assigneeId: 'user-1',
    priority: 'medium',
    tags: ['planning', 'product'],
    createdAt: '2024-03-20T10:00:00Z',
    fileChanges: ['docs/roadmap/q2-plan.md', 'docs/roadmap/review-notes.md'],
    comments: [
      { id: 'c1', authorId: 'user-1', authorName: 'Hritvik', content: 'Keep the milestones lean and investor-readable.', timestamp: '2024-03-20T11:00:00Z', type: 'user' },
      { id: 'c2', authorId: 'agent-1', authorName: 'Kay', content: 'I am tightening the roadmap and translating it into a board-ready narrative.', timestamp: '2024-03-20T11:05:00Z', type: 'agent' }
    ]
  },
  {
    id: 'issue-102',
    title: 'Audit acquisition funnel drop-offs',
    description: 'Identify where demo traffic is leaking and propose three testable conversion hypotheses.',
    status: 'in-progress',
    agentId: 'agent-3',
    assigneeId: 'user-1',
    priority: 'high',
    tags: ['growth', 'conversion'],
    createdAt: '2024-03-19T14:30:00Z',
    fileChanges: ['analysis/funnel-audit.sql', 'marketing/landing-tests.md'],
    comments: []
  },
  {
    id: 'issue-103',
    title: 'Ship auth service regression coverage',
    description: 'Increase test coverage for the authentication middleware and resolve edge-case session failures.',
    status: 'todo',
    priority: 'low',
    tags: ['testing', 'backend'],
    createdAt: '2024-03-21T09:15:00Z',
    comments: []
  },
  {
    id: 'issue-104',
    title: 'Review AI infrastructure spend anomalies',
    description: 'Explain the jump in provider costs and identify where request efficiency can be improved.',
    status: 'backlog',
    priority: 'medium',
    tags: ['finance', 'infra'],
    createdAt: '2024-03-18T16:45:00Z',
    comments: []
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  { id: 'act-1', agentId: 'agent-1', type: 'status_updated', message: 'Reframed the roadmap into three board-level bets with explicit owners.', timestamp: '2024-03-21T11:20:00Z', issueId: 'issue-101' },
  { id: 'act-2', agentId: 'agent-3', type: 'work_started', message: 'Started a fresh funnel audit across paid, direct, and product-led entry points.', timestamp: '2024-03-21T10:45:00Z', issueId: 'issue-102' },
  { id: 'act-3', agentId: 'agent-6', type: 'blocker_reported', message: 'Flagged missing session expiry traces in the auth middleware test matrix.', timestamp: '2024-03-21T09:30:00Z', issueId: 'issue-103' },
  { id: 'act-4', agentId: 'agent-9', type: 'code_pushed', message: 'Published a revised spend model with provider-level cost breakouts.', timestamp: '2024-03-21T08:40:00Z', issueId: 'issue-104' },
];

export const MOCK_SKILLS: Skill[] = [
  { id: 's1', name: 'Roadmap Planning', description: 'Prioritizing product bets and sequencing execution', category: 'research', level: 88 },
  { id: 's2', name: 'Growth Experimentation', description: 'Running structured funnel and messaging tests', category: 'research', level: 79 },
  { id: 's3', name: 'Backend Reliability', description: 'Hardening APIs, auth flows, and infrastructure edges', category: 'coding', level: 91 },
  { id: 's4', name: 'Revenue Operations', description: 'Managing pipeline systems and outbound operations', category: 'devops', level: 73 },
];
