"""
OAuth provider configurations — single source of truth.
"""

OAUTH_PROVIDERS = {
    "google": {
        "name": "Gmail",
        "icon": "mail",
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": "https://www.googleapis.com/auth/gmail.modify",
    },
    "slack": {
        "name": "Slack",
        "icon": "message-circle",
        "auth_url": "https://slack.com/oauth/v2/authorize",
        "token_url": "https://slack.com/api/oauth.v2.access",
        "scopes": "channels:read,channels:history,groups:read,groups:history,chat:write,chat:write.public,im:write,im:history,im:read,users:read,files:write,files:read,reactions:write",
    },
    "notion": {
        "name": "Notion",
        "icon": "file-text",
        "auth_url": "https://api.notion.com/v1/oauth/authorize",
        "token_url": "https://api.notion.com/v1/oauth/token",
        "scopes": "",
    },
    "github": {
        "name": "GitHub",
        "icon": "github",
        "auth_url": "https://github.com/login/oauth/authorize",
        "token_url": "https://github.com/login/oauth/access_token",
        "scopes": "repo,user,read:org",
    },
    "jira": {
        "name": "Jira",
        "icon": "briefcase",
        "auth_url": "https://auth.atlassian.com/authorize",
        "token_url": "https://auth.atlassian.com/oauth/token",
        "scopes": "read:jira-work write:jira-work offline_access",
    },
    "salesforce": {
        "name": "Salesforce",
        "icon": "cloud",
        "auth_url": "https://login.salesforce.com/services/oauth2/authorize",
        "token_url": "https://login.salesforce.com/services/oauth2/token",
        "scopes": "api refresh_token",
    },
    "linear": {
        "name": "Linear",
        "icon": "git-commit",
        "auth_url": "https://linear.app/oauth/authorize",
        "token_url": "https://api.linear.app/oauth/token",
        "scopes": "read write",
    },
    "hubspot": {
        "name": "Hubspot",
        "icon": "share-2",
        "auth_url": "https://app.hubspot.com/oauth/authorize",
        "token_url": "https://api.hubapi.com/oauth/v1/token",
        "scopes": "contacts content reports",
    },
    "stripe": {
        "name": "Stripe",
        "icon": "credit-card",
        "auth_url": "https://connect.stripe.com/oauth/authorize",
        "token_url": "https://connect.stripe.com/oauth/token",
        "scopes": "read_write",
    },
    "google_drive": {
        "name": "Google Drive",
        "icon": "hard-drive",
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": "https://www.googleapis.com/auth/drive",
    },
    "google_calendar": {
        "name": "Google Calendar",
        "icon": "calendar",
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": "https://www.googleapis.com/auth/calendar",
    },
    # --- Newly added OAuth providers ---
    "airtable": {
        "name": "Airtable",
        "icon": "table",
        "auth_url": "https://airtable.com/oauth2/v1/authorize",
        "token_url": "https://airtable.com/oauth2/v1/token",
        "scopes": "data.records:read data.records:write schema.bases:read schema.bases:write",
    },
    "asana": {
        "name": "Asana",
        "icon": "check-square",
        "auth_url": "https://app.asana.com/-/oauth_authorize",
        "token_url": "https://app.asana.com/-/oauth_token",
        "scopes": "default",
    },
    "attio": {
        "name": "Attio",
        "icon": "users",
        "auth_url": "https://app.attio.com/oauth/authorize",
        "token_url": "https://app.attio.com/oauth/token",
        "scopes": "record_permission:read record_permission:read-write object_configuration:read list_configuration:read",
    },
    "box": {
        "name": "Box",
        "icon": "box",
        "auth_url": "https://account.box.com/api/oauth2/authorize",
        "token_url": "https://api.box.com/oauth2/token",
        "scopes": "root_readwrite",
    },
    "box_sign": {
        "name": "Box Sign",
        "icon": "pen-tool",
        "auth_url": "https://account.box.com/api/oauth2/authorize",
        "token_url": "https://api.box.com/oauth2/token",
        "scopes": "sign_requests.readwrite root_readwrite",
    },
    "calcom": {
        "name": "Cal.com",
        "icon": "calendar-check",
        "auth_url": "https://app.cal.com/auth/oauth2/authorize",
        "token_url": "https://api.cal.com/v2/auth/oauth2/token",
        "scopes": "BOOKING_READ BOOKING_WRITE PROFILE_READ",
    },
    "confluence": {
        "name": "Confluence",
        "icon": "book-open",
        "auth_url": "https://auth.atlassian.com/authorize",
        "token_url": "https://auth.atlassian.com/oauth/token",
        "scopes": "read:confluence-space.summary write:confluence-content read:confluence-content.all offline_access",
    },
    "docusign": {
        "name": "DocuSign",
        "icon": "file-check",
        "auth_url": "https://account.docusign.com/oauth/auth",
        "token_url": "https://account.docusign.com/oauth/token",
        "scopes": "signature impersonation",
    },
    "dropbox": {
        "name": "Dropbox",
        "icon": "dropbox",
        "auth_url": "https://www.dropbox.com/oauth2/authorize",
        "token_url": "https://api.dropboxapi.com/oauth2/token",
        "scopes": "files.content.read files.content.write sharing.write",
    },
    "google_ads": {
        "name": "Google Ads",
        "icon": "trending-up",
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": "https://www.googleapis.com/auth/adwords",
    },
    "google_bigquery": {
        "name": "Google BigQuery",
        "icon": "database",
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": "https://www.googleapis.com/auth/bigquery",
    },
    "google_docs": {
        "name": "Google Docs",
        "icon": "file-text",
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": "https://www.googleapis.com/auth/documents",
    },
    "google_forms": {
        "name": "Google Forms",
        "icon": "clipboard",
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": "https://www.googleapis.com/auth/forms.body https://www.googleapis.com/auth/forms.responses.readonly",
    },
    "google_meet": {
        "name": "Google Meet",
        "icon": "video",
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": "https://www.googleapis.com/auth/meetings.space.created",
    },
    "google_sheets": {
        "name": "Google Sheets",
        "icon": "grid",
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": "https://www.googleapis.com/auth/spreadsheets",
    },
    "google_slides": {
        "name": "Google Slides",
        "icon": "layout",
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": "https://www.googleapis.com/auth/presentations",
    },
    "google_tasks": {
        "name": "Google Tasks",
        "icon": "check-circle",
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": "https://www.googleapis.com/auth/tasks",
    },
    "microsoft_dataverse": {
        "name": "Microsoft Dataverse",
        "icon": "database",
        "auth_url": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "token_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        "scopes": "https://globaldisco.crm.dynamics.com/user_impersonation offline_access",
    },
    "microsoft_excel": {
        "name": "Microsoft Excel",
        "icon": "file-spreadsheet",
        "auth_url": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "token_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        "scopes": "Files.ReadWrite offline_access",
    },
    "microsoft_planner": {
        "name": "Microsoft Planner",
        "icon": "layout-list",
        "auth_url": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "token_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        "scopes": "Tasks.ReadWrite offline_access",
    },
    "microsoft_teams": {
        "name": "Microsoft Teams",
        "icon": "users",
        "auth_url": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "token_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        "scopes": "ChannelMessage.Send Chat.ReadWrite offline_access",
    },
    "outlook": {
        "name": "Outlook",
        "icon": "mail",
        "auth_url": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "token_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        "scopes": "Mail.ReadWrite Mail.Send offline_access",
    },
    "pipedrive": {
        "name": "Pipedrive",
        "icon": "git-merge",
        "auth_url": "https://oauth.pipedrive.com/oauth/authorize",
        "token_url": "https://oauth.pipedrive.com/oauth/token",
        "scopes": "base deals persons organizations",
    },
    "reddit": {
        "name": "Reddit",
        "icon": "message-square",
        "auth_url": "https://www.reddit.com/api/v1/authorize",
        "token_url": "https://www.reddit.com/api/v1/access_token",
        "scopes": "read submit identity",
    },
    "shopify": {
        "name": "Shopify",
        "icon": "shopping-bag",
        "auth_url": "https://{shop}.myshopify.com/admin/oauth/authorize",
        "token_url": "https://{shop}.myshopify.com/admin/oauth/access_token",
        "scopes": "read_products write_products read_orders write_orders read_customers",
    },
    "webflow": {
        "name": "Webflow",
        "icon": "globe",
        "auth_url": "https://webflow.com/oauth/authorize",
        "token_url": "https://api.webflow.com/oauth/access_token",
        "scopes": "cms:read cms:write sites:read",
    },
    "wordpress": {
        "name": "WordPress",
        "icon": "edit-3",
        "auth_url": "https://public-api.wordpress.com/oauth2/authorize",
        "token_url": "https://public-api.wordpress.com/oauth2/token",
        "scopes": "global",
    },
    "x": {
        "name": "X (Twitter)",
        "icon": "twitter",
        "auth_url": "https://twitter.com/i/oauth2/authorize",
        "token_url": "https://api.twitter.com/2/oauth2/token",
        "scopes": "tweet.read tweet.write users.read offline.access",
    },
    "zoom": {
        "name": "Zoom",
        "icon": "video",
        "auth_url": "https://zoom.us/oauth/authorize",
        "token_url": "https://zoom.us/oauth/token",
        "scopes": "meeting:read meeting:write user:read",
    },
}

# API-key-based integrations — no OAuth redirect, just store keys in credentials table.
# fields: list of {key, label, secret, required} that the user must provide.
API_KEY_PROVIDERS = {
    "agentmail": {
        "name": "Agentmail",
        "icon": "mail",
        "fields": [{"key": "agentmail_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "ahrefs": {
        "name": "Ahrefs",
        "icon": "bar-chart-2",
        "fields": [{"key": "AHREFS_API_KEY", "label": "API Key", "secret": True, "required": True}],
    },
    "airweave": {
        "name": "Airweave",
        "icon": "wind",
        "fields": [{"key": "airweave_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "apollo": {
        "name": "Apollo",
        "icon": "target",
        "fields": [{"key": "apollo_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "ashby": {
        "name": "Ashby",
        "icon": "users",
        "fields": [{"key": "ashby_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "cursor": {
        "name": "Cursor",
        "icon": "mouse-pointer",
        "fields": [{"key": "cursor_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "datadog": {
        "name": "Datadog",
        "icon": "activity",
        "fields": [
            {"key": "DATADOG_API_KEY", "label": "API Key", "secret": True, "required": True},
            {"key": "DATADOG_APPLICATION_KEY", "label": "Application Key", "secret": True, "required": True},
            {"key": "DATADOG_SITE", "label": "Site (e.g. datadoghq.com)", "secret": False, "required": False},
        ],
    },
    "devin": {
        "name": "Devin",
        "icon": "cpu",
        "fields": [{"key": "devin_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "discord": {
        "name": "Discord",
        "icon": "message-circle",
        "fields": [{"key": "discord_bot_token", "label": "Bot Token", "secret": True, "required": True}],
    },
    "evernote": {
        "name": "Evernote",
        "icon": "book",
        "fields": [{"key": "evernote_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "exa": {
        "name": "Exa",
        "icon": "search",
        "fields": [{"key": "EXA_API_KEY", "label": "API Key", "secret": True, "required": True}],
    },
    "extend": {
        "name": "Extend",
        "icon": "zap",
        "fields": [{"key": "extend_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "firecrawl": {
        "name": "Firecrawl",
        "icon": "flame",
        "fields": [{"key": "FIRECRAWL_API_KEY", "label": "API Key", "secret": True, "required": True}],
    },
    "gamma": {
        "name": "Gamma",
        "icon": "layers",
        "fields": [{"key": "gamma_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "gitlab": {
        "name": "GitLab",
        "icon": "gitlab",
        "fields": [{"key": "gitlab_api_key", "label": "Personal Access Token", "secret": True, "required": True}],
    },
    "gong": {
        "name": "Gong",
        "icon": "phone-call",
        "fields": [
            {"key": "gong_access_key", "label": "Access Key", "secret": True, "required": True},
            {"key": "gong_access_key_secret", "label": "Access Key Secret", "secret": True, "required": True},
        ],
    },
    "google_maps": {
        "name": "Google Maps",
        "icon": "map-pin",
        "fields": [{"key": "GOOGLE_MAPS_API_KEY", "label": "API Key", "secret": True, "required": True}],
    },
    "granola": {
        "name": "Granola",
        "icon": "mic",
        "fields": [{"key": "granola_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "greenhouse": {
        "name": "Greenhouse",
        "icon": "users",
        "fields": [{"key": "greenhouse_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "hex": {
        "name": "Hex",
        "icon": "hexagon",
        "fields": [{"key": "hex_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "hunter": {
        "name": "Hunter",
        "icon": "crosshair",
        "fields": [{"key": "hunter_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "incidentio": {
        "name": "Incident.io",
        "icon": "alert-triangle",
        "fields": [{"key": "incidentio_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "intercom": {
        "name": "Intercom",
        "icon": "message-circle",
        "fields": [{"key": "intercom_api_key", "label": "Access Token", "secret": True, "required": True}],
    },
    "kalshi": {
        "name": "Kalshi",
        "icon": "trending-up",
        "fields": [{"key": "kalshi_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "langsmith": {
        "name": "LangSmith",
        "icon": "link",
        "fields": [{"key": "langsmith_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "loops": {
        "name": "Loops",
        "icon": "repeat",
        "fields": [{"key": "loops_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "luma": {
        "name": "Luma",
        "icon": "sun",
        "fields": [{"key": "luma_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "pagerduty": {
        "name": "PagerDuty",
        "icon": "bell",
        "fields": [{"key": "pagerduty_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "reducto": {
        "name": "Reducto",
        "icon": "scissors",
        "fields": [{"key": "reducto_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "sixtyfour": {
        "name": "64 Squares",
        "icon": "grid",
        "fields": [{"key": "sixtyfour_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "trello": {
        "name": "Trello",
        "icon": "trello",
        "fields": [
            {"key": "trello_api_key", "label": "API Key", "secret": True, "required": True},
            {"key": "trello_token", "label": "Token", "secret": True, "required": True},
        ],
    },
    "vercel": {
        "name": "Vercel",
        "icon": "triangle",
        "fields": [{"key": "vercel_api_key", "label": "API Token", "secret": True, "required": True}],
    },
    "youtube": {
        "name": "YouTube",
        "icon": "youtube",
        "fields": [{"key": "youtube_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    "zendesk": {
        "name": "Zendesk",
        "icon": "headphones",
        "fields": [
            {"key": "zendesk_api_key", "label": "API Token", "secret": True, "required": True},
            {"key": "zendesk_subdomain", "label": "Subdomain (e.g. mycompany)", "secret": False, "required": True},
            {"key": "zendesk_email", "label": "Agent Email", "secret": False, "required": True},
        ],
    },
    "zep": {
        "name": "Zep",
        "icon": "zap",
        "fields": [{"key": "zep_api_key", "label": "API Key", "secret": True, "required": True}],
    },
    # Infrastructure / connection-string tools
    "aws": {
        "name": "AWS (S3 / CloudWatch)",
        "icon": "cloud",
        "fields": [
            {"key": "AWS_ACCESS_KEY_ID", "label": "Access Key ID", "secret": True, "required": True},
            {"key": "AWS_SECRET_ACCESS_KEY", "label": "Secret Access Key", "secret": True, "required": True},
            {"key": "AWS_DEFAULT_REGION", "label": "Region (e.g. us-east-1)", "secret": False, "required": False},
        ],
    },
    "neo4j": {
        "name": "Neo4j",
        "icon": "share-2",
        "fields": [
            {"key": "NEO4J_URI", "label": "Connection URI (bolt://...)", "secret": False, "required": True},
            {"key": "NEO4J_USERNAME", "label": "Username", "secret": False, "required": True},
            {"key": "NEO4J_PASSWORD", "label": "Password", "secret": True, "required": True},
        ],
    },
    "postgresql": {
        "name": "PostgreSQL",
        "icon": "database",
        "fields": [
            {"key": "POSTGRESQL_HOST", "label": "Host", "secret": False, "required": True},
            {"key": "POSTGRESQL_PORT", "label": "Port (default 5432)", "secret": False, "required": False},
            {"key": "POSTGRESQL_DATABASE", "label": "Database name", "secret": False, "required": True},
            {"key": "POSTGRESQL_USERNAME", "label": "Username", "secret": False, "required": True},
            {"key": "POSTGRESQL_PASSWORD", "label": "Password", "secret": True, "required": True},
        ],
    },
    "redis": {
        "name": "Redis",
        "icon": "server",
        "fields": [
            {"key": "REDIS_URL", "label": "Redis URL (redis://user:pass@host:port)", "secret": True, "required": True},
        ],
    },
    "databricks": {
        "name": "Databricks",
        "icon": "cpu",
        "fields": [
            {"key": "DATABRICKS_HOST", "label": "Host (https://xxx.azuredatabricks.net)", "secret": False, "required": True},
            {"key": "DATABRICKS_API_KEY", "label": "Personal Access Token", "secret": True, "required": True},
        ],
    },
    "workday": {
        "name": "Workday",
        "icon": "briefcase",
        "fields": [
            {"key": "WORKDAY_TENANT_URL", "label": "Tenant URL", "secret": False, "required": True},
            {"key": "WORKDAY_TENANT", "label": "Tenant name", "secret": False, "required": True},
            {"key": "WORKDAY_USERNAME", "label": "Username", "secret": False, "required": True},
            {"key": "WORKDAY_PASSWORD", "label": "Password", "secret": True, "required": True},
        ],
    },
    "video": {
        "name": "Video (Fal.ai)",
        "icon": "film",
        "fields": [
            {"key": "FAL_API_KEY", "label": "Fal.ai API Key", "secret": True, "required": True},
        ],
    },
    "sms": {
        "name": "SMS (Twilio)",
        "icon": "message-square",
        "fields": [
            {"key": "TWILIO_ACCOUNT_SID", "label": "Account SID", "secret": False, "required": True},
            {"key": "TWILIO_AUTH_TOKEN", "label": "Auth Token", "secret": True, "required": True},
            {"key": "TWILIO_FROM_NUMBER", "label": "From Number (e.g. +15551234567)", "secret": False, "required": True},
        ],
    },
}
