// Auto-generated from .reference/sim landing integrations data

export type SimIntegrationMeta = {
  type: string;
  slug: string;
  name: string;
  bgColor: string;
  iconName: string;
};

export const SIM_INTEGRATIONS_BY_TYPE: Record<string, SimIntegrationMeta> = {
  'a2a': { type: 'a2a', slug: 'a2a', name: "A2A", bgColor: '#4151B5', iconName: 'A2AIcon' },
  'agentmail': { type: 'agentmail', slug: 'agentmail', name: "AgentMail", bgColor: '#000000', iconName: 'AgentMailIcon' },
  'ahrefs': { type: 'ahrefs', slug: 'ahrefs', name: "Ahrefs", bgColor: '#E0E0E0', iconName: 'AhrefsIcon' },
  'airtable': { type: 'airtable', slug: 'airtable', name: "Airtable", bgColor: '#E0E0E0', iconName: 'AirtableIcon' },
  'airweave': { type: 'airweave', slug: 'airweave', name: "Airweave", bgColor: '#6366F1', iconName: 'AirweaveIcon' },
  'algolia': { type: 'algolia', slug: 'algolia', name: "Algolia", bgColor: '#003DFF', iconName: 'AlgoliaIcon' },
  'amplitude': { type: 'amplitude', slug: 'amplitude', name: "Amplitude", bgColor: '#1B1F3B', iconName: 'AmplitudeIcon' },
  'apify': { type: 'apify', slug: 'apify', name: "Apify", bgColor: '#E0E0E0', iconName: 'ApifyIcon' },
  'apollo': { type: 'apollo', slug: 'apollo', name: "Apollo", bgColor: '#EBF212', iconName: 'ApolloIcon' },
  'arxiv': { type: 'arxiv', slug: 'arxiv', name: "ArXiv", bgColor: '#E0E0E0', iconName: 'ArxivIcon' },
  'asana': { type: 'asana', slug: 'asana', name: "Asana", bgColor: '#E0E0E0', iconName: 'AsanaIcon' },
  'ashby': { type: 'ashby', slug: 'ashby', name: "Ashby", bgColor: '#5D4ED6', iconName: 'AshbyIcon' },
  'attio': { type: 'attio', slug: 'attio', name: "Attio", bgColor: '#1D1E20', iconName: 'AttioIcon' },
  'box': { type: 'box', slug: 'box', name: "Box", bgColor: '#FFFFFF', iconName: 'BoxCompanyIcon' },
  'brandfetch': { type: 'brandfetch', slug: 'brandfetch', name: "Brandfetch", bgColor: '#000000', iconName: 'BrandfetchIcon' },
  'browser_use': { type: 'browser_use', slug: 'browser-use', name: "Browser Use", bgColor: '#181C1E', iconName: 'BrowserUseIcon' },
  'calcom': { type: 'calcom', slug: 'cal-com', name: "Cal Com", bgColor: '#FFFFFE', iconName: 'CalComIcon' },
  'calendly': { type: 'calendly', slug: 'calendly', name: "Calendly", bgColor: '#FFFFFF', iconName: 'CalendlyIcon' },
  'circleback': { type: 'circleback', slug: 'circleback', name: "Circleback", bgColor: 'linear-gradient(180deg, #E0F7FA 0%, #FFFFFF 100%)', iconName: 'CirclebackIcon' },
  'clay': { type: 'clay', slug: 'clay', name: "Clay", bgColor: '#E0E0E0', iconName: 'ClayIcon' },
  'clerk': { type: 'clerk', slug: 'clerk', name: "Clerk", bgColor: '#131316', iconName: 'ClerkIcon' },
  'cloudflare': { type: 'cloudflare', slug: 'cloudflare', name: "Cloudflare", bgColor: '#F5F6FA', iconName: 'CloudflareIcon' },
  'cloudformation': { type: 'cloudformation', slug: 'cloudformation', name: "CloudFormation", bgColor: 'linear-gradient(45deg, #B0084D 0%, #FF4F8B 100%)', iconName: 'CloudFormationIcon' },
  'cloudwatch': { type: 'cloudwatch', slug: 'cloudwatch', name: "CloudWatch", bgColor: 'linear-gradient(45deg, #B0084D 0%, #FF4F8B 100%)', iconName: 'CloudWatchIcon' },
  'confluence_v2': { type: 'confluence_v2', slug: 'confluence', name: "Confluence", bgColor: '#E0E0E0', iconName: 'ConfluenceIcon' },
  'cursor_v2': { type: 'cursor_v2', slug: 'cursor', name: "Cursor", bgColor: '#1E1E1E', iconName: 'CursorIcon' },
  'databricks': { type: 'databricks', slug: 'databricks', name: "Databricks", bgColor: '#F9F7F4', iconName: 'DatabricksIcon' },
  'datadog': { type: 'datadog', slug: 'datadog', name: "Datadog", bgColor: '#632CA6', iconName: 'DatadogIcon' },
  'devin': { type: 'devin', slug: 'devin', name: "Devin", bgColor: '#12141A', iconName: 'DevinIcon' },
  'discord': { type: 'discord', slug: 'discord', name: "Discord", bgColor: '#5865F2', iconName: 'DiscordIcon' },
  'docusign': { type: 'docusign', slug: 'docusign', name: "DocuSign", bgColor: '#FFFFFF', iconName: 'DocuSignIcon' },
  'dropbox': { type: 'dropbox', slug: 'dropbox', name: "Dropbox", bgColor: '#0061FF', iconName: 'DropboxIcon' },
  'dspy': { type: 'dspy', slug: 'dspy', name: "DSPy", bgColor: '#E0E0E0', iconName: 'DsPyIcon' },
  'dub': { type: 'dub', slug: 'dub', name: "Dub", bgColor: '#181C1E', iconName: 'DubIcon' },
  'duckduckgo': { type: 'duckduckgo', slug: 'duckduckgo', name: "DuckDuckGo", bgColor: '#FFFFFF', iconName: 'DuckDuckGoIcon' },
  'dynamodb': { type: 'dynamodb', slug: 'amazon-dynamodb', name: "Amazon DynamoDB", bgColor: 'linear-gradient(45deg, #2E27AD 0%, #527FFF 100%)', iconName: 'DynamoDBIcon' },
  'elasticsearch': { type: 'elasticsearch', slug: 'elasticsearch', name: "Elasticsearch", bgColor: '#E0E0E0', iconName: 'ElasticsearchIcon' },
  'elevenlabs': { type: 'elevenlabs', slug: 'elevenlabs', name: "ElevenLabs", bgColor: '#181C1E', iconName: 'ElevenLabsIcon' },
  'enrich': { type: 'enrich', slug: 'enrich', name: "Enrich", bgColor: '#E5E5E6', iconName: 'EnrichSoIcon' },
  'evernote': { type: 'evernote', slug: 'evernote', name: "Evernote", bgColor: '#E0E0E0', iconName: 'EvernoteIcon' },
  'exa': { type: 'exa', slug: 'exa', name: "Exa", bgColor: '#1F40ED', iconName: 'ExaAIIcon' },
  'extend_v2': { type: 'extend_v2', slug: 'extend', name: "Extend", bgColor: '#000000', iconName: 'ExtendIcon' },
  'fathom': { type: 'fathom', slug: 'fathom', name: "Fathom", bgColor: '#181C1E', iconName: 'FathomIcon' },
  'file_v3': { type: 'file_v3', slug: 'file', name: "File", bgColor: '#40916C', iconName: 'DocumentIcon' },
  'firecrawl': { type: 'firecrawl', slug: 'firecrawl', name: "Firecrawl", bgColor: '#181C1E', iconName: 'FirecrawlIcon' },
  'fireflies_v2': { type: 'fireflies_v2', slug: 'fireflies', name: "Fireflies", bgColor: '#100730', iconName: 'FirefliesIcon' },
  'gamma': { type: 'gamma', slug: 'gamma', name: "Gamma", bgColor: '#002253', iconName: 'GammaIcon' },
  'github_v2': { type: 'github_v2', slug: 'github', name: "GitHub", bgColor: '#181C1E', iconName: 'GithubIcon' },
  'gitlab': { type: 'gitlab', slug: 'gitlab', name: "GitLab", bgColor: '#E0E0E0', iconName: 'GitLabIcon' },
  'gmail_v2': { type: 'gmail_v2', slug: 'gmail', name: "Gmail", bgColor: '#E0E0E0', iconName: 'GmailIcon' },
  'gong': { type: 'gong', slug: 'gong', name: "Gong", bgColor: '#8039DF', iconName: 'GongIcon' },
  'google_ads': { type: 'google_ads', slug: 'google-ads', name: "Google Ads", bgColor: '#E0E0E0', iconName: 'GoogleAdsIcon' },
  'google_bigquery': { type: 'google_bigquery', slug: 'google-bigquery', name: "Google BigQuery", bgColor: '#E0E0E0', iconName: 'GoogleBigQueryIcon' },
  'google_books': { type: 'google_books', slug: 'google-books', name: "Google Books", bgColor: '#E0E0E0', iconName: 'GoogleBooksIcon' },
  'google_calendar_v2': { type: 'google_calendar_v2', slug: 'google-calendar', name: "Google Calendar", bgColor: '#E0E0E0', iconName: 'GoogleCalendarIcon' },
  'google_contacts': { type: 'google_contacts', slug: 'google-contacts', name: "Google Contacts", bgColor: '#E0E0E0', iconName: 'GoogleContactsIcon' },
  'google_docs': { type: 'google_docs', slug: 'google-docs', name: "Google Docs", bgColor: '#E0E0E0', iconName: 'GoogleDocsIcon' },
  'google_drive': { type: 'google_drive', slug: 'google-drive', name: "Google Drive", bgColor: '#E0E0E0', iconName: 'GoogleDriveIcon' },
  'google_forms': { type: 'google_forms', slug: 'google-forms', name: "Google Forms", bgColor: '#E0E0E0', iconName: 'GoogleFormsIcon' },
  'google_groups': { type: 'google_groups', slug: 'google-groups', name: "Google Groups", bgColor: '#E8F0FE', iconName: 'GoogleGroupsIcon' },
  'google_maps': { type: 'google_maps', slug: 'google-maps', name: "Google Maps", bgColor: '#E0E0E0', iconName: 'GoogleMapsIcon' },
  'google_meet': { type: 'google_meet', slug: 'google-meet', name: "Google Meet", bgColor: '#E0E0E0', iconName: 'GoogleMeetIcon' },
  'google_pagespeed': { type: 'google_pagespeed', slug: 'google-pagespeed', name: "Google PageSpeed", bgColor: '#E0E0E0', iconName: 'GooglePagespeedIcon' },
  'google_search': { type: 'google_search', slug: 'google-search', name: "Google Search", bgColor: '#E0E0E0', iconName: 'GoogleIcon' },
  'google_sheets_v2': { type: 'google_sheets_v2', slug: 'google-sheets', name: "Google Sheets", bgColor: '#E0E0E0', iconName: 'GoogleSheetsIcon' },
  'google_slides_v2': { type: 'google_slides_v2', slug: 'google-slides', name: "Google Slides", bgColor: '#E0E0E0', iconName: 'GoogleSlidesIcon' },
  'google_tasks': { type: 'google_tasks', slug: 'google-tasks', name: "Google Tasks", bgColor: '#E0E0E0', iconName: 'GoogleTasksIcon' },
  'google_translate': { type: 'google_translate', slug: 'google-translate', name: "Google Translate", bgColor: '#E0E0E0', iconName: 'GoogleTranslateIcon' },
  'google_vault': { type: 'google_vault', slug: 'google-vault', name: "Google Vault", bgColor: '#E8F0FE', iconName: 'GoogleVaultIcon' },
  'grafana': { type: 'grafana', slug: 'grafana', name: "Grafana", bgColor: '#E0E0E0', iconName: 'GrafanaIcon' },
  'grain': { type: 'grain', slug: 'grain', name: "Grain", bgColor: '#F6FAF9', iconName: 'GrainIcon' },
  'granola': { type: 'granola', slug: 'granola', name: "Granola", bgColor: '#B2C147', iconName: 'GranolaIcon' },
  'greenhouse': { type: 'greenhouse', slug: 'greenhouse', name: "Greenhouse", bgColor: '#469776', iconName: 'GreenhouseIcon' },
  'greptile': { type: 'greptile', slug: 'greptile', name: "Greptile", bgColor: '#e5e5e5', iconName: 'GreptileIcon' },
  'hex': { type: 'hex', slug: 'hex', name: "Hex", bgColor: '#14151A', iconName: 'HexIcon' },
  'hubspot': { type: 'hubspot', slug: 'hubspot', name: "HubSpot", bgColor: '#FF7A59', iconName: 'HubspotIcon' },
  'huggingface': { type: 'huggingface', slug: 'hugging-face', name: "Hugging Face", bgColor: '#0B0F19', iconName: 'HuggingFaceIcon' },
  'hunter': { type: 'hunter', slug: 'hunter-io', name: "Hunter io", bgColor: '#E0E0E0', iconName: 'HunterIOIcon' },
  'image_generator': { type: 'image_generator', slug: 'image-generator', name: "Image Generator", bgColor: '#4D5FFF', iconName: 'ImageIcon' },
  'imap': { type: 'imap', slug: 'imap-email', name: "IMAP Email", bgColor: '#6366F1', iconName: 'MailServerIcon' },
  'incidentio': { type: 'incidentio', slug: 'incidentio', name: "incidentio", bgColor: '#E0E0E0', iconName: 'IncidentioIcon' },
  'infisical': { type: 'infisical', slug: 'infisical', name: "Infisical", bgColor: '#F7FE62', iconName: 'InfisicalIcon' },
  'intercom_v2': { type: 'intercom_v2', slug: 'intercom', name: "Intercom", bgColor: '#E0E0E0', iconName: 'IntercomIcon' },
  'jina': { type: 'jina', slug: 'jina', name: "Jina", bgColor: '#333333', iconName: 'JinaAIIcon' },
  'jira': { type: 'jira', slug: 'jira', name: "Jira", bgColor: '#E0E0E0', iconName: 'JiraIcon' },
  'jira_service_management': { type: 'jira_service_management', slug: 'jira-service-management', name: "Jira Service Management", bgColor: '#E0E0E0', iconName: 'JiraServiceManagementIcon' },
  'kalshi_v2': { type: 'kalshi_v2', slug: 'kalshi', name: "Kalshi", bgColor: '#09C285', iconName: 'KalshiIcon' },
  'ketch': { type: 'ketch', slug: 'ketch', name: "Ketch", bgColor: '#9B5CFF', iconName: 'KetchIcon' },
  'knowledge': { type: 'knowledge', slug: 'knowledge', name: "Knowledge", bgColor: '#00B0B0', iconName: 'PackageSearchIcon' },
  'langsmith': { type: 'langsmith', slug: 'langsmith', name: "LangSmith", bgColor: '#181C1E', iconName: 'LangsmithIcon' },
  'launchdarkly': { type: 'launchdarkly', slug: 'launchdarkly', name: "LaunchDarkly", bgColor: '#191919', iconName: 'LaunchDarklyIcon' },
  'lemlist': { type: 'lemlist', slug: 'lemlist', name: "Lemlist", bgColor: '#316BFF', iconName: 'LemlistIcon' },
  'linear_v2': { type: 'linear_v2', slug: 'linear', name: "Linear", bgColor: '#5E6AD2', iconName: 'LinearIcon' },
  'linkedin': { type: 'linkedin', slug: 'linkedin', name: "LinkedIn", bgColor: '#0072B1', iconName: 'LinkedInIcon' },
  'linkup': { type: 'linkup', slug: 'linkup', name: "Linkup", bgColor: '#D6D3C7', iconName: 'LinkupIcon' },
  'loops': { type: 'loops', slug: 'loops', name: "Loops", bgColor: '#FAFAF9', iconName: 'LoopsIcon' },
  'luma': { type: 'luma', slug: 'luma', name: "Luma", bgColor: '#FFFFFF', iconName: 'LumaIcon' },
  'mailchimp': { type: 'mailchimp', slug: 'mailchimp', name: "Mailchimp", bgColor: '#FFE01B', iconName: 'MailchimpIcon' },
  'mailgun': { type: 'mailgun', slug: 'mailgun', name: "Mailgun", bgColor: '#E0E0E0', iconName: 'MailgunIcon' },
  'mem0': { type: 'mem0', slug: 'mem0', name: "Mem0", bgColor: '#181C1E', iconName: 'Mem0Icon' },
  'memory': { type: 'memory', slug: 'memory', name: "Memory", bgColor: '#F64F9E', iconName: 'BrainIcon' },
  'microsoft_ad': { type: 'microsoft_ad', slug: 'azure-ad', name: "Azure AD", bgColor: '#0078D4', iconName: 'AzureIcon' },
  'microsoft_dataverse': { type: 'microsoft_dataverse', slug: 'microsoft-dataverse', name: "Microsoft Dataverse", bgColor: '#E0E0E0', iconName: 'MicrosoftDataverseIcon' },
  'microsoft_excel_v2': { type: 'microsoft_excel_v2', slug: 'microsoft-excel', name: "Microsoft Excel", bgColor: '#E0E0E0', iconName: 'MicrosoftExcelIcon' },
  'microsoft_planner': { type: 'microsoft_planner', slug: 'microsoft-planner', name: "Microsoft Planner", bgColor: '#E0E0E0', iconName: 'MicrosoftPlannerIcon' },
  'microsoft_teams': { type: 'microsoft_teams', slug: 'microsoft-teams', name: "Microsoft Teams", bgColor: '#E0E0E0', iconName: 'MicrosoftTeamsIcon' },
  'mistral_parse_v3': { type: 'mistral_parse_v3', slug: 'mistral-parser', name: "Mistral Parser", bgColor: '#000000', iconName: 'MistralIcon' },
  'mongodb': { type: 'mongodb', slug: 'mongodb', name: "MongoDB", bgColor: '#E0E0E0', iconName: 'MongoDBIcon' },
  'mysql': { type: 'mysql', slug: 'mysql', name: "MySQL", bgColor: '#E0E0E0', iconName: 'MySQLIcon' },
  'neo4j': { type: 'neo4j', slug: 'neo4j', name: "Neo4j", bgColor: '#FFFFFF', iconName: 'Neo4jIcon' },
  'notion_v2': { type: 'notion_v2', slug: 'notion', name: "Notion", bgColor: '#181C1E', iconName: 'NotionIcon' },
  'obsidian': { type: 'obsidian', slug: 'obsidian', name: "Obsidian", bgColor: '#0F0F0F', iconName: 'ObsidianIcon' },
  'okta': { type: 'okta', slug: 'okta', name: "Okta", bgColor: '#191919', iconName: 'OktaIcon' },
  'onedrive': { type: 'onedrive', slug: 'onedrive', name: "OneDrive", bgColor: '#E0E0E0', iconName: 'MicrosoftOneDriveIcon' },
  'onepassword': { type: 'onepassword', slug: '1password', name: "1Password", bgColor: '#E0E0E0', iconName: 'OnePasswordIcon' },
  'openai': { type: 'openai', slug: 'embeddings', name: "Embeddings", bgColor: '#10a37f', iconName: 'OpenAIIcon' },
  'outlook': { type: 'outlook', slug: 'outlook', name: "Outlook", bgColor: '#E0E0E0', iconName: 'OutlookIcon' },
  'pagerduty': { type: 'pagerduty', slug: 'pagerduty', name: "PagerDuty", bgColor: '#06AC38', iconName: 'PagerDutyIcon' },
  'parallel_ai': { type: 'parallel_ai', slug: 'parallel-ai', name: "Parallel AI", bgColor: '#E0E0E0', iconName: 'ParallelIcon' },
  'perplexity': { type: 'perplexity', slug: 'perplexity', name: "Perplexity", bgColor: '#20808D', iconName: 'PerplexityIcon' },
  'pinecone': { type: 'pinecone', slug: 'pinecone', name: "Pinecone", bgColor: '#0D1117', iconName: 'PineconeIcon' },
  'pipedrive': { type: 'pipedrive', slug: 'pipedrive', name: "Pipedrive", bgColor: '#2E6936', iconName: 'PipedriveIcon' },
  'polymarket': { type: 'polymarket', slug: 'polymarket', name: "Polymarket", bgColor: '#4C82FB', iconName: 'PolymarketIcon' },
  'postgresql': { type: 'postgresql', slug: 'postgresql', name: "PostgreSQL", bgColor: '#336791', iconName: 'PostgresIcon' },
  'posthog': { type: 'posthog', slug: 'posthog', name: "PostHog", bgColor: '#E0E0E0', iconName: 'PosthogIcon' },
  'profound': { type: 'profound', slug: 'profound', name: "Profound", bgColor: '#000000', iconName: 'ProfoundIcon' },
  'pulse_v2': { type: 'pulse_v2', slug: 'pulse', name: "Pulse", bgColor: '#E0E0E0', iconName: 'PulseIcon' },
  'qdrant': { type: 'qdrant', slug: 'qdrant', name: "Qdrant", bgColor: '#1A223F', iconName: 'QdrantIcon' },
  'quiver': { type: 'quiver', slug: 'quiver', name: "Quiver", bgColor: '#000000', iconName: 'QuiverIcon' },
  'rds': { type: 'rds', slug: 'amazon-rds', name: "Amazon RDS", bgColor: 'linear-gradient(45deg, #2E27AD 0%, #527FFF 100%)', iconName: 'RDSIcon' },
  'reddit': { type: 'reddit', slug: 'reddit', name: "Reddit", bgColor: '#FF5700', iconName: 'RedditIcon' },
  'redis': { type: 'redis', slug: 'redis', name: "Redis", bgColor: '#FF4438', iconName: 'RedisIcon' },
  'reducto_v2': { type: 'reducto_v2', slug: 'reducto', name: "Reducto", bgColor: '#5c0c5c', iconName: 'ReductoIcon' },
  'resend': { type: 'resend', slug: 'resend', name: "Resend", bgColor: '#181C1E', iconName: 'ResendIcon' },
  'revenuecat': { type: 'revenuecat', slug: 'revenuecat', name: "RevenueCat", bgColor: '#F25A5A', iconName: 'RevenueCatIcon' },
  'rippling': { type: 'rippling', slug: 'rippling', name: "Rippling", bgColor: '#FFCC1C', iconName: 'RipplingIcon' },
  'rootly': { type: 'rootly', slug: 'rootly', name: "Rootly", bgColor: '#6C72C8', iconName: 'RootlyIcon' },
  's3': { type: 's3', slug: 's3', name: "S3", bgColor: 'linear-gradient(45deg, #1B660F 0%, #6CAE3E 100%)', iconName: 'S3Icon' },
  'salesforce': { type: 'salesforce', slug: 'salesforce', name: "Salesforce", bgColor: '#E0E0E0', iconName: 'SalesforceIcon' },
  'search': { type: 'search', slug: 'search', name: "Search", bgColor: '#3B82F6', iconName: 'SearchIcon' },
  'secrets_manager': { type: 'secrets_manager', slug: 'aws-secrets-manager', name: "AWS Secrets Manager", bgColor: 'linear-gradient(45deg, #BD0816 0%, #FF5252 100%)', iconName: 'SecretsManagerIcon' },
  'sendgrid': { type: 'sendgrid', slug: 'sendgrid', name: "SendGrid", bgColor: '#1A82E2', iconName: 'SendgridIcon' },
  'sentry': { type: 'sentry', slug: 'sentry', name: "Sentry", bgColor: '#E0E0E0', iconName: 'SentryIcon' },
  'serper': { type: 'serper', slug: 'serper', name: "Serper", bgColor: '#2B3543', iconName: 'SerperIcon' },
  'servicenow': { type: 'servicenow', slug: 'servicenow', name: "ServiceNow", bgColor: '#032D42', iconName: 'ServiceNowIcon' },
  'sftp': { type: 'sftp', slug: 'sftp', name: "SFTP", bgColor: '#2D3748', iconName: 'SftpIcon' },
  'sharepoint': { type: 'sharepoint', slug: 'sharepoint', name: "Sharepoint", bgColor: '#E0E0E0', iconName: 'MicrosoftSharepointIcon' },
  'shopify': { type: 'shopify', slug: 'shopify', name: "Shopify", bgColor: '#FFFFFF', iconName: 'ShopifyIcon' },
  'similarweb': { type: 'similarweb', slug: 'similarweb', name: "Similarweb", bgColor: '#000922', iconName: 'SimilarwebIcon' },
  'sixtyfour': { type: 'sixtyfour', slug: 'sixtyfour-ai', name: "Sixtyfour AI", bgColor: '#000000', iconName: 'SixtyfourIcon' },
  'slack': { type: 'slack', slug: 'slack', name: "Slack", bgColor: '#611f69', iconName: 'SlackIcon' },
  'smtp': { type: 'smtp', slug: 'smtp', name: "SMTP", bgColor: '#2D3748', iconName: 'SmtpIcon' },
  'sqs': { type: 'sqs', slug: 'amazon-sqs', name: "Amazon SQS", bgColor: 'linear-gradient(45deg, #2E27AD 0%, #527FFF 100%)', iconName: 'SQSIcon' },
  'ssh': { type: 'ssh', slug: 'ssh', name: "SSH", bgColor: '#000000', iconName: 'SshIcon' },
  'stagehand': { type: 'stagehand', slug: 'stagehand', name: "Stagehand", bgColor: '#FFC83C', iconName: 'StagehandIcon' },
  'stripe': { type: 'stripe', slug: 'stripe', name: "Stripe", bgColor: '#635BFF', iconName: 'StripeIcon' },
  'stt_v2': { type: 'stt_v2', slug: 'speech-to-text', name: "Speech-to-Text", bgColor: '#181C1E', iconName: 'STTIcon' },
  'supabase': { type: 'supabase', slug: 'supabase', name: "Supabase", bgColor: '#1C1C1C', iconName: 'SupabaseIcon' },
  'tailscale': { type: 'tailscale', slug: 'tailscale', name: "Tailscale", bgColor: '#2E2D2D', iconName: 'TailscaleIcon' },
  'tavily': { type: 'tavily', slug: 'tavily', name: "Tavily", bgColor: '#0066FF', iconName: 'TavilyIcon' },
  'telegram': { type: 'telegram', slug: 'telegram', name: "Telegram", bgColor: '#E0E0E0', iconName: 'TelegramIcon' },
  'textract_v2': { type: 'textract_v2', slug: 'aws-textract', name: "AWS Textract", bgColor: 'linear-gradient(135deg, #055F4E 0%, #56C0A7 100%)', iconName: 'TextractIcon' },
  'tinybird': { type: 'tinybird', slug: 'tinybird', name: "Tinybird", bgColor: '#2EF598', iconName: 'TinybirdIcon' },
  'translate': { type: 'translate', slug: 'translate', name: "Translate", bgColor: '#FF4B4B', iconName: 'TranslateIcon' },
  'trello': { type: 'trello', slug: 'trello', name: "Trello", bgColor: '#0052CC', iconName: 'TrelloIcon' },
  'tts': { type: 'tts', slug: 'text-to-speech', name: "Text-to-Speech", bgColor: '#181C1E', iconName: 'TTSIcon' },
  'twilio_sms': { type: 'twilio_sms', slug: 'twilio-sms', name: "Twilio SMS", bgColor: '#F22F46', iconName: 'TwilioIcon' },
  'twilio_voice': { type: 'twilio_voice', slug: 'twilio-voice', name: "Twilio Voice", bgColor: '#F22F46', iconName: 'TwilioIcon' },
  'typeform': { type: 'typeform', slug: 'typeform', name: "Typeform", bgColor: '#262627', iconName: 'TypeformIcon' },
  'upstash': { type: 'upstash', slug: 'upstash', name: "Upstash", bgColor: '#181C1E', iconName: 'UpstashIcon' },
  'vercel': { type: 'vercel', slug: 'vercel', name: "Vercel", bgColor: '#171717', iconName: 'VercelIcon' },
  'video_generator_v2': { type: 'video_generator_v2', slug: 'video-generator', name: "Video Generator", bgColor: '#181C1E', iconName: 'VideoIcon' },
  'vision_v2': { type: 'vision_v2', slug: 'vision', name: "Vision", bgColor: '#4D5FFF', iconName: 'EyeIcon' },
  'wealthbox': { type: 'wealthbox', slug: 'wealthbox', name: "Wealthbox", bgColor: '#E0E0E0', iconName: 'WealthboxIcon' },
  'webflow': { type: 'webflow', slug: 'webflow', name: "Webflow", bgColor: '#E0E0E0', iconName: 'WebflowIcon' },
  'whatsapp': { type: 'whatsapp', slug: 'whatsapp', name: "WhatsApp", bgColor: '#25D366', iconName: 'WhatsAppIcon' },
  'wikipedia': { type: 'wikipedia', slug: 'wikipedia', name: "Wikipedia", bgColor: '#000000', iconName: 'WikipediaIcon' },
  'wordpress': { type: 'wordpress', slug: 'wordpress', name: "WordPress", bgColor: '#21759B', iconName: 'WordpressIcon' },
  'workday': { type: 'workday', slug: 'workday', name: "Workday", bgColor: '#F5F0EB', iconName: 'WorkdayIcon' },
  'x': { type: 'x', slug: 'x', name: "X", bgColor: '#000000', iconName: 'xIcon' },
  'youtube': { type: 'youtube', slug: 'youtube', name: "YouTube", bgColor: '#FF0000', iconName: 'YouTubeIcon' },
  'zendesk': { type: 'zendesk', slug: 'zendesk', name: "Zendesk", bgColor: '#E0E0E0', iconName: 'ZendeskIcon' },
  'zep': { type: 'zep', slug: 'zep', name: "Zep", bgColor: '#E8E8E8', iconName: 'ZepIcon' },
  'zoom': { type: 'zoom', slug: 'zoom', name: "Zoom", bgColor: '#2D8CFF', iconName: 'ZoomIcon' },
};

export const SIM_TYPE_BY_ALIAS: Record<string, string> = {
  '1password': 'onepassword',
  'a2a': 'a2a',
  'agentmail': 'agentmail',
  'ahrefs': 'ahrefs',
  'airtable': 'airtable',
  'airweave': 'airweave',
  'algolia': 'algolia',
  'amazon dynamodb': 'dynamodb',
  'amazon rds': 'rds',
  'amazon sqs': 'sqs',
  'amazon-dynamodb': 'dynamodb',
  'amazon-rds': 'rds',
  'amazon-sqs': 'sqs',
  'amazon_dynamodb': 'dynamodb',
  'amazon_rds': 'rds',
  'amazon_sqs': 'sqs',
  'amazondynamodb': 'dynamodb',
  'amazonrds': 'rds',
  'amazonsqs': 'sqs',
  'amplitude': 'amplitude',
  'apify': 'apify',
  'apollo': 'apollo',
  'arxiv': 'arxiv',
  'asana': 'asana',
  'ashby': 'ashby',
  'attio': 'attio',
  'aws': 's3',
  'aws secrets manager': 'secrets_manager',
  'aws textract': 'textract_v2',
  'aws-secrets-manager': 'secrets_manager',
  'aws-textract': 'textract_v2',
  'aws_secrets_manager': 'secrets_manager',
  'aws_textract': 'textract_v2',
  'awssecretsmanager': 'secrets_manager',
  'awstextract': 'textract_v2',
  'azure ad': 'microsoft_ad',
  'azure-ad': 'microsoft_ad',
  'azure_ad': 'microsoft_ad',
  'azuread': 'microsoft_ad',
  'box': 'box',
  'box_sign': 'box',
  'brandfetch': 'brandfetch',
  'browser use': 'browser_use',
  'browser-use': 'browser_use',
  'browser_use': 'browser_use',
  'browseruse': 'browser_use',
  'cal com': 'calcom',
  'cal-com': 'calcom',
  'cal_com': 'calcom',
  'calcom': 'calcom',
  'calendly': 'calendly',
  'circleback': 'circleback',
  'clay': 'clay',
  'clerk': 'clerk',
  'cloudflare': 'cloudflare',
  'cloudformation': 'cloudformation',
  'cloudwatch': 'cloudwatch',
  'confluence': 'confluence_v2',
  'confluence_v2': 'confluence_v2',
  'confluencev2': 'confluence_v2',
  'cursor': 'cursor_v2',
  'cursor_v2': 'cursor_v2',
  'cursorv2': 'cursor_v2',
  'databricks': 'databricks',
  'datadog': 'datadog',
  'devin': 'devin',
  'discord': 'discord',
  'docusign': 'docusign',
  'dropbox': 'dropbox',
  'dspy': 'dspy',
  'dub': 'dub',
  'duckduckgo': 'duckduckgo',
  'dynamodb': 'dynamodb',
  'elasticsearch': 'elasticsearch',
  'elevenlabs': 'elevenlabs',
  'embeddings': 'openai',
  'enrich': 'enrich',
  'evernote': 'evernote',
  'exa': 'exa',
  'extend': 'extend_v2',
  'extend_v2': 'extend_v2',
  'extendv2': 'extend_v2',
  'fal': 'video_generator_v2',
  'fal_ai': 'video_generator_v2',
  'fathom': 'fathom',
  'file': 'file_v3',
  'file_v3': 'file_v3',
  'filev3': 'file_v3',
  'firecrawl': 'firecrawl',
  'fireflies': 'fireflies_v2',
  'fireflies_v2': 'fireflies_v2',
  'firefliesv2': 'fireflies_v2',
  'gamma': 'gamma',
  'github': 'github_v2',
  'github_v2': 'github_v2',
  'githubv2': 'github_v2',
  'gitlab': 'gitlab',
  'gmail': 'gmail_v2',
  'gmail_v2': 'gmail_v2',
  'gmailv2': 'gmail_v2',
  'gong': 'gong',
  'google': 'google_search',
  'google ads': 'google_ads',
  'google bigquery': 'google_bigquery',
  'google books': 'google_books',
  'google calendar': 'google_calendar_v2',
  'google contacts': 'google_contacts',
  'google docs': 'google_docs',
  'google drive': 'google_drive',
  'google forms': 'google_forms',
  'google groups': 'google_groups',
  'google maps': 'google_maps',
  'google meet': 'google_meet',
  'google pagespeed': 'google_pagespeed',
  'google search': 'google_search',
  'google sheets': 'google_sheets_v2',
  'google slides': 'google_slides_v2',
  'google tasks': 'google_tasks',
  'google translate': 'google_translate',
  'google vault': 'google_vault',
  'google-ads': 'google_ads',
  'google-bigquery': 'google_bigquery',
  'google-books': 'google_books',
  'google-calendar': 'google_calendar_v2',
  'google-contacts': 'google_contacts',
  'google-docs': 'google_docs',
  'google-drive': 'google_drive',
  'google-forms': 'google_forms',
  'google-groups': 'google_groups',
  'google-maps': 'google_maps',
  'google-meet': 'google_meet',
  'google-pagespeed': 'google_pagespeed',
  'google-search': 'google_search',
  'google-sheets': 'google_sheets_v2',
  'google-slides': 'google_slides_v2',
  'google-tasks': 'google_tasks',
  'google-translate': 'google_translate',
  'google-vault': 'google_vault',
  'google_ads': 'google_ads',
  'google_bigquery': 'google_bigquery',
  'google_books': 'google_books',
  'google_calendar': 'google_calendar_v2',
  'google_calendar_v2': 'google_calendar_v2',
  'google_contacts': 'google_contacts',
  'google_docs': 'google_docs',
  'google_drive': 'google_drive',
  'google_forms': 'google_forms',
  'google_groups': 'google_groups',
  'google_maps': 'google_maps',
  'google_meet': 'google_meet',
  'google_pagespeed': 'google_pagespeed',
  'google_search': 'google_search',
  'google_sheets': 'google_sheets_v2',
  'google_sheets_v2': 'google_sheets_v2',
  'google_slides': 'google_slides_v2',
  'google_slides_v2': 'google_slides_v2',
  'google_tasks': 'google_tasks',
  'google_translate': 'google_translate',
  'google_vault': 'google_vault',
  'googleads': 'google_ads',
  'googlebigquery': 'google_bigquery',
  'googlebooks': 'google_books',
  'googlecalendar': 'google_calendar_v2',
  'googlecalendarv2': 'google_calendar_v2',
  'googlecontacts': 'google_contacts',
  'googledocs': 'google_docs',
  'googledrive': 'google_drive',
  'googleforms': 'google_forms',
  'googlegroups': 'google_groups',
  'googlemaps': 'google_maps',
  'googlemeet': 'google_meet',
  'googlepagespeed': 'google_pagespeed',
  'googlesearch': 'google_search',
  'googlesheets': 'google_sheets_v2',
  'googlesheetsv2': 'google_sheets_v2',
  'googleslides': 'google_slides_v2',
  'googleslidesv2': 'google_slides_v2',
  'googletasks': 'google_tasks',
  'googletranslate': 'google_translate',
  'googlevault': 'google_vault',
  'grafana': 'grafana',
  'grain': 'grain',
  'granola': 'granola',
  'greenhouse': 'greenhouse',
  'greptile': 'greptile',
  'hex': 'hex',
  'hubspot': 'hubspot',
  'hugging face': 'huggingface',
  'hugging-face': 'huggingface',
  'hugging_face': 'huggingface',
  'huggingface': 'huggingface',
  'hunter': 'hunter',
  'hunter io': 'hunter',
  'hunter-io': 'hunter',
  'hunter_io': 'hunter',
  'hunterio': 'hunter',
  'image generator': 'image_generator',
  'image-generator': 'image_generator',
  'image_generator': 'image_generator',
  'imagegenerator': 'image_generator',
  'imap': 'imap',
  'imap email': 'imap',
  'imap-email': 'imap',
  'imap_email': 'imap',
  'imapemail': 'imap',
  'incidentio': 'incidentio',
  'infisical': 'infisical',
  'intercom': 'intercom_v2',
  'intercom_v2': 'intercom_v2',
  'intercomv2': 'intercom_v2',
  'jina': 'jina',
  'jira': 'jira',
  'jira service management': 'jira_service_management',
  'jira-service-management': 'jira_service_management',
  'jira_service_management': 'jira_service_management',
  'jiraservicemanagement': 'jira_service_management',
  'kalshi': 'kalshi_v2',
  'kalshi_v2': 'kalshi_v2',
  'kalshiv2': 'kalshi_v2',
  'ketch': 'ketch',
  'knowledge': 'knowledge',
  'langsmith': 'langsmith',
  'launchdarkly': 'launchdarkly',
  'lemlist': 'lemlist',
  'linear': 'linear_v2',
  'linear_v2': 'linear_v2',
  'linearv2': 'linear_v2',
  'linkedin': 'linkedin',
  'linkup': 'linkup',
  'loops': 'loops',
  'luma': 'luma',
  'mailchimp': 'mailchimp',
  'mailgun': 'mailgun',
  'mem0': 'mem0',
  'memory': 'memory',
  'microsoft dataverse': 'microsoft_dataverse',
  'microsoft excel': 'microsoft_excel_v2',
  'microsoft planner': 'microsoft_planner',
  'microsoft teams': 'microsoft_teams',
  'microsoft-dataverse': 'microsoft_dataverse',
  'microsoft-excel': 'microsoft_excel_v2',
  'microsoft-planner': 'microsoft_planner',
  'microsoft-teams': 'microsoft_teams',
  'microsoft_ad': 'microsoft_ad',
  'microsoft_dataverse': 'microsoft_dataverse',
  'microsoft_excel': 'microsoft_excel_v2',
  'microsoft_excel_v2': 'microsoft_excel_v2',
  'microsoft_planner': 'microsoft_planner',
  'microsoft_teams': 'microsoft_teams',
  'microsoftad': 'microsoft_ad',
  'microsoftdataverse': 'microsoft_dataverse',
  'microsoftexcel': 'microsoft_excel_v2',
  'microsoftexcelv2': 'microsoft_excel_v2',
  'microsoftplanner': 'microsoft_planner',
  'microsoftteams': 'microsoft_teams',
  'mistral parser': 'mistral_parse_v3',
  'mistral-parser': 'mistral_parse_v3',
  'mistral_parse': 'mistral_parse_v3',
  'mistral_parse_v3': 'mistral_parse_v3',
  'mistral_parser': 'mistral_parse_v3',
  'mistralparser': 'mistral_parse_v3',
  'mistralparsev3': 'mistral_parse_v3',
  'mongodb': 'mongodb',
  'mysql': 'mysql',
  'neo4j': 'neo4j',
  'notion': 'notion_v2',
  'notion_v2': 'notion_v2',
  'notionv2': 'notion_v2',
  'obsidian': 'obsidian',
  'okta': 'okta',
  'onedrive': 'onedrive',
  'onepassword': 'onepassword',
  'openai': 'openai',
  'outlook': 'outlook',
  'pagerduty': 'pagerduty',
  'parallel ai': 'parallel_ai',
  'parallel-ai': 'parallel_ai',
  'parallel_ai': 'parallel_ai',
  'parallelai': 'parallel_ai',
  'perplexity': 'perplexity',
  'pinecone': 'pinecone',
  'pipedrive': 'pipedrive',
  'polymarket': 'polymarket',
  'postgresql': 'postgresql',
  'posthog': 'posthog',
  'profound': 'profound',
  'pulse': 'pulse_v2',
  'pulse_v2': 'pulse_v2',
  'pulsev2': 'pulse_v2',
  'qdrant': 'qdrant',
  'quiver': 'quiver',
  'rds': 'rds',
  'reddit': 'reddit',
  'redis': 'redis',
  'reducto': 'reducto_v2',
  'reducto_v2': 'reducto_v2',
  'reductov2': 'reducto_v2',
  'resend': 'resend',
  'revenuecat': 'revenuecat',
  'rippling': 'rippling',
  'rootly': 'rootly',
  's3': 's3',
  'salesforce': 'salesforce',
  'search': 'search',
  'secrets_manager': 'secrets_manager',
  'secretsmanager': 'secrets_manager',
  'sendgrid': 'sendgrid',
  'sentry': 'sentry',
  'serper': 'serper',
  'servicenow': 'servicenow',
  'sftp': 'sftp',
  'sharepoint': 'sharepoint',
  'shopify': 'shopify',
  'similarweb': 'similarweb',
  'sixtyfour': 'sixtyfour',
  'sixtyfour ai': 'sixtyfour',
  'sixtyfour-ai': 'sixtyfour',
  'sixtyfour_ai': 'sixtyfour',
  'sixtyfourai': 'sixtyfour',
  'slack': 'slack',
  'sms': 'twilio_sms',
  'smtp': 'smtp',
  'speech-to-text': 'stt_v2',
  'speech_to_text': 'stt_v2',
  'speechtotext': 'stt_v2',
  'sqs': 'sqs',
  'ssh': 'ssh',
  'stagehand': 'stagehand',
  'stripe': 'stripe',
  'stt': 'stt_v2',
  'stt_v2': 'stt_v2',
  'sttv2': 'stt_v2',
  'supabase': 'supabase',
  'tailscale': 'tailscale',
  'tavily': 'tavily',
  'telegram': 'telegram',
  'text-to-speech': 'tts',
  'text_to_speech': 'tts',
  'textract': 'textract_v2',
  'textract_v2': 'textract_v2',
  'textractv2': 'textract_v2',
  'texttospeech': 'tts',
  'tinybird': 'tinybird',
  'translate': 'translate',
  'trello': 'trello',
  'tts': 'tts',
  'twilio': 'twilio_sms',
  'twilio sms': 'twilio_sms',
  'twilio voice': 'twilio_voice',
  'twilio-sms': 'twilio_sms',
  'twilio-voice': 'twilio_voice',
  'twilio_sms': 'twilio_sms',
  'twilio_voice': 'twilio_voice',
  'twiliosms': 'twilio_sms',
  'twiliovoice': 'twilio_voice',
  'typeform': 'typeform',
  'upstash': 'upstash',
  'vercel': 'vercel',
  'video': 'video_generator_v2',
  'video generator': 'video_generator_v2',
  'video-generator': 'video_generator_v2',
  'video_generator': 'video_generator_v2',
  'video_generator_v2': 'video_generator_v2',
  'videogenerator': 'video_generator_v2',
  'videogeneratorv2': 'video_generator_v2',
  'vision': 'vision_v2',
  'vision_v2': 'vision_v2',
  'visionv2': 'vision_v2',
  'wealthbox': 'wealthbox',
  'webflow': 'webflow',
  'whatsapp': 'whatsapp',
  'wikipedia': 'wikipedia',
  'wordpress': 'wordpress',
  'workday': 'workday',
  'x': 'x',
  'youtube': 'youtube',
  'zendesk': 'zendesk',
  'zep': 'zep',
  'zoom': 'zoom',
};
